CREATE DATABASE BANKING_SYSTEMDB;
USE BANKING_SYSTEMDB;

SHOW DATABASES;
SHOW TABLES;

CREATE TABLE CUSTOMERS(
CUSTOMERID INT,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAIL VARCHAR(100),
PHONE VARCHAR(10));

DESCRIBE TABLE CUSTOMERS;
DESCRIBE CUSTOMERS;

SELECT *
FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN ACCOUNTCREATIONDATE DATE;

CREATE TABLE ACCOUNTS(
ACCOUNTID INT,
ACCOUNTYPE VARCHAR(20),
BALANCE DECIMAL(10,2));

CREATE TABLE TRANSACTION(
TRANSACTIONID INT,
TRANSACTIONDATE DATE,
AMOUNT DECIMAL(10,2),
TRANSACTIONTYPE VARCHAR(20));

CREATE TABLE BRANCHES(
BRANCHID INT,
BRANCHNAME VARCHAR(100),
BRANCHADDRESS VARCHAR(255),
BRANCHPHONE VARCHAR(20));

CREATE TABLE ACCOUNTBRANCHES(
ASSIGNEDATE DATE);

CREATE TABLE LOANS(
LOANID INT,
LAONAMOUNT DECIMAL(10,2),
INTERESTRATE DECIMAL (5,2),
STARTDATE DATE,
ENDDATE DATE);

SHOW TABLES;

ALTER TABLE CUSTOMERS
DROP COLUMN ACCOUNTCREATIONDATE;

SELECT *
FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN BIRTHDATE DATE;



ALTER TABLE CUSTOMERS
MODIFY PHONE VARCHAR(20),
ADD PRIMARY KEY (CUSTOMERID);

DESCRIBE CUSTOMERS;

SELECT *
FROM ACCOUNTS;

ALTER TABLE ACCOUNTS 
ADD CUSTOMERID INT;

ALTER TABLE ACCOUNTS
ADD CONSTRAINT 
FOREIGN KEY (CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);

DESCRIBE ACCOUNTS;

ALTER TABLE ACCOUNTS 
ADD PRIMARY KEY (ACCOUNTID);

ALTER TABLE TRANSACTION 
ADD ACCOUNTID INT,
ADD CONSTRAINT
FOREIGN KEY (ACCOUNTID)
REFERENCES ACCOUNTS(ACCOUNTID);


DESCRIBE ACCOUNTS;
DESCRIBE TRANSACTION;

ALTER TABLE TRANSACTION
ADD PRIMARY KEY (TRANSACTIONID);

DESCRIBE TRANSACTION;

ALTER TABLE BRANCHES
ADD PRIMARY KEY (BRANCHID);

ALTER TABLE ACCOUNTS
ADD BRANCHID INT,
ADD CONSTRAINT
FOREIGN KEY (BRANCHID)
REFERENCES BRANCHES(BRANCHID);

ALTER TABLE LOANS
ADD PRIMARY KEY (LOANID),
ADD CUSTOMERID INT,
ADD CONSTRAINT
FOREIGN KEY (CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);

ALTER TABLE  CUSTOMERS
MODIFY FIRSTNAME VARCHAR(50) NOT NULL,
MODIFY EMAIL VARCHAR(100) UNIQUE;

DESCRIBE CUSTOMERS;
USE BANKING_SYSTEMDB;


INSERT INTO CUSTOMERS VALUE
(101,'Rahul','Sharma','rahul.sharma@gmail.com','9767983712','1995-04-12');


INSERT INTO CUSTOMERS VALUE
(102,'Veena','Kutty','veena.kutty@gmail.com','1234567890','1997-09-10'),
(103,'Dominic','Dom','dominic.dom@gmail.com','NULL','1996-06-03'),
(104,'Alex','NULL'customerstransaction,'alex@gmail.com','3232323232','2000-12-12'),
(105,'Alice','George','Null','9090909090','2000-08-10');

SELECT *
FROM CUSTOMERS;

INSERT INTO BRANCHES (BRANCHID,BRANCHNAME,BRANCHADDRESS,BRANCHPHONE)
VALUE(1,'Mumbai Main Branch','Andheri East Mumbai','0220100201'),
(2,'Pune Central Branch','Shivaji Nagar Pune','0220100202'),
(3,'Banglore Branch','MG Road Banglore','0880100801'),
(4,'Delhi Branch','Connaught palace Delhi',NULL),
(5,'Hydrabad Branch',NULL,'0440100401');

SELECT *
FROM BRANCHES;

INSERT INTO ACCOUNTS VALUES
(1001,'SAVING',25000,101,1),
(1002,'CURRENT',85000.50,102,2),
(1003,'SAVING',12500.75,103,1),
(1004,'SALARY',45000,104,3),
(1005,'SAVING',7800.25,105,2),
(1006,'SAVING',42000,101,2),
(1007,'CURRENT',NULL,103,2),
(1008,'SAVING',27500,105,4);

INSERT INTO TRANSACTION VALUES
(5001,'2026-01-05',10000,'DEPOSIT',1001),
(5002,'2026-01-10',2500,'WITHDRAWAL',1001),
(5003,'2026-01-15',5000,'TRANSFER',1002),
(5004,'2026-01-20',15000,'DEPOSIT',1003),
(5005,'2026-01-25',3000,'WITHDRAWAL',1004),
(5006,'2026-02-02',7500,'DEPOSIT',1005),
(5007,'2026-02-05',1200,'PAYMENT',1006),
(5008,'2026-02-10',NULL,'DEPOSIT',1007),
(5009,'2026-02-15',8500,'WITHDRAWAL',1008),
(50010,NULL,100,'PAYMENT',1003),
(5011,'2026-02-20',20000,'TRANSFER',1006),
(5012,'2026-03-01',5000,'DEPOSIT',1002),
(5013,'2026-03-05',10000,'WITHDRAWAL',1007),
(5014,'2026-03-15',1500,'DEPOSIT',1008),
(5015,'2026-02-20',25000,'TRANSFER',1005);

SELECT *
FROM TRANSACTION;

INSERT INTO LOANS VALUES
(9001,50000,8.50,'2025-01-15','2023-01-15',101),
(9002,250000,9.25,'2025-03-10','2028-03-10',103),
(9003,NULL,9.00,'2026-03-01',NULL,105),
(9004,750000,7.90,'2024-06-20','2031-06-20',102),
(9005,1000000,7.25,'2024-11-15','2034-11-15',104),
(9006,300000,10.50,'2025-07-01','2029-07-01',101);

-- CHECKING THE DATA

SELECT *
FROM CUSTOMERS;

SELECT *
FROM BRANCHES;

SELECT *
FROM ACCOUNTS;

SELECT *
FROM TRANSACTION;

SELECT *
FROM LOANS;

USE BANKING_SYSTEMDB;

-- UPDATING AND DELETING RECORDS 

UPDATE CUSTOMERS
SET PHONE = "4345667890"
WHERE CUSTOMERID = 103; -- UPDATED A PHONE  NUMBER        

DELETE FROM TRANSACTION 
WHERE TRANSACTIONID =5008; -- UPDATED A USELESS RECORD 

UPDATE ACCOUNTS 
SET BALANCE = 35750 
WHERE ACCOUNTID = 1007; -- UPDATED THE BALANCE 

-- EXTRACTING DATA 

SELECT FIRSTNAME,EMAIL,CUSTOMERID
FROM CUSTOMERS;

SELECT * 
FROM CUSTOMERS
WHERE CUSTOMERID = 105; -- CALLING SPECIFIC DATA  

SELECT * 
FROM CUSTOMERS
WHERE CUSTOMERID = 102 OR CUSTOMERID = 104; -- CALLING MULTIPLE ID

SELECT * -- CALLING DATA IN RANGE 
FROM CUSTOMERS
WHERE BIRTHDATE >= '1995-01-01' AND BIRTHDATE <='2000-12-31';


UPDATE TRANSACTION
SET ACCOUNTID = 1003
WHERE TRANSACTIONID IN (5006,5007); -- UPDATED MULTIPLE RECORDS 


USE BANKING_SYSTEMDB;


-- Customer Analysis --

-- How many customers are there ?

SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMERS;

-- which customers have missing information ?

SELECT CUSTOMERID, FIRSTNAME AS NAME 
FROM CUSTOMERS
WHERE LASTNAME IS NULL OR EMAIL IS NULL;

SELECT *
FROM CUSTOMERS;

-- Who are the youngest/Oldest customers?

SELECT
MAX(BIRTHDATE) AS YOUNGEST_CUSTOMER,
MIN(BIRTHDATE) AS OLDEST_CUSTOMER
FROM CUSTOMERS;

-- Howmany customers were born before/after a particular year ?

-- before 2000 --

SELECT *
FROM CUSTOMERS
WHERE YEAR(BIRTHDATE) <2000;

-- AFTER 2000---
SELECT *
FROM CUSTOMERS
WHERE YEAR(BIRTHDATE) >= 2000;

SELECT *
FROM CUSTOMERS;

-- which custoners have miulktiplea accounts

SELECT CUSTOMERID, COUNT(*) AS TOTAL_ACCOUNTS
FROM ACCOUNTS
GROUP BY CUSTOMERID
HAVING TOTAL_ACCOUNTS > 1;


-- Account Analysis

-- how may saving ,current and salary accounts exist ?

SELECT ACCOUNTYPE,COUNT(*) AS TOTAL_ACCOUNTS
FROM ACCOUNTS
GROUP BY ACCOUNTYPE;

-- What is the total balalnce ?

SELECT SUM(BALANCE) TOTAL_BALANCE
FROM ACCOUNTS;

-- What is the average account balance ?

SELECT AVG(BALANCE) AVERAGE_BALANCE
FROM ACCOUNTS;

-- Which customers have the highest balances?

SELECT CUSTOMERID, BALANCE HIGHEST_BALANCE 
FROM ACCOUNTS 
ORDER BY BALANCE DESC LIMIT 1;

-- Which accounts have Null balance ?

SELECT *
FROM ACCOUNTS
WHERE BALANCE =NULL;

-- Which branch manages the most accounts ?

SELECT BRANCHID, COUNT(*) TOTAL_ACCOUNTS
FROM ACCOUNTS 
GROUP BY BRANCHID
ORDER BY TOTAL_ACCOUNTS DESC LIMIT 1;


-- TRANSACTION ANALYSIS 

-- what is the  total transaction amount?

SELECT SUM(AMOUNT) TOTAL_TRANSACTION_AMOUNT
FROM TRANSACTION;

-- howmany deposits/withdrawls/transfers are there ?

SELECT TRANSACTIONTYPE, COUNT(*) TOTAL_TRANSACTIONS
FROM TRANSACTION
WHERE TRANSACTIONTYPE IN ('DEPOSIT','WITHDRAWAL','TRANSFER')
GROUP BY TRANSACTIONTYPE;

-- Which transaction type has the highest volume ?

SELECT TRANSACTIONTYPE, SUM(AMOUNT) TOTAL_AMOUNT 
FROM TRANSACTION
GROUP BY TRANSACTIONTYPE
ORDER BY TOTAL_AMOUNT DESC LIMIT 1;


-- which account has the highest transaction activity ?

SELECT ACCOUNTID , COUNT(*) TOTAL_TRANSACTIONS
FROM TRANSACTION
GROUP BY ACCOUNTID
ORDER BY TOTAL_TRANSACTIONS DESC LIMIT 1;

-- What is the average transaction amount  ? 

SELECT AVG(AMOUNT) AVERAGE_TRANSACTION 
FROM TRANSACTION;

-- Which transaction have missing dates/amounts ?

SELECT *
FROM TRANSACTION
WHERE TRANSACTIONDATE IS NULL OR AMOUNT IS NULL; 

USE BANKING_SYSTEMDB;


-- LOAN ANALYSIS

-- what is the total loan amount ?

SELECT	SUM(LAONAMOUNT) TOTAL_LOANS
FROM LOANS;

-- Which customer has the largest loan?

SELECT CUSTOMERID, SUM(LAONAMOUNT) TOTAL_LOANS
FROM LOANS
GROUP BY CUSTOMERID
ORDER BY TOTAL_LOANS DESC LIMIT 1;

-- Which loan has the highest interest rate ?

SELECT MAX(INTERESTRATE) HIGHEST_INTEREST_RATE
FROM LOANS;

-- which loans are still active ?

SELECT *
FROM LOANS
WHERE YEAR(ENDDATE)>2026;

-- Which customer have multiple loans ?

SELECT CUSTOMERID, COUNT(*) TOTAL_LOANS
FROM LOANS
GROUP BY CUSTOMERID
HAVING TOTAL_LOANS>1;

-- What is the average loan amount ?

SELECT AVG(LAONAMOUNT) AVERAGE_LOAN_AMOUNT
FROM LOANS;


-- BRANCH ANALYSIS

-- Which branch has the most customers/accounts?

-- Branch with most accounts 

SELECT BRANCHID, COUNT(*) TOTAL_ACCOUNTS
FROM ACCOUNTS
GROUP BY BRANCHID 
ORDER BY TOTAL_ACCOUNTS DESC LIMIT 1;

-- branch with most customers

SELECT BRANCHID, COUNT(CUSTOMERID) TOTAL_CUSTOMERS
FROM ACCOUNTS 
GROUP BY BRANCHID
ORDER BY TOTAL_CUSTOMERS DESC LIMIT  1;

-- Which branch has  the highest total account balanc ?

SELECT BRANCHID, SUM(BALANCE) TOTAL_BALANCE
FROM ACCOUNTS
GROUP BY BRANCHID 
ORDER BY TOTAL_BALANCE DESC LIMIT 1;

-- Which branch handles the most transaction  ?

-- Accounts with MAX transaction

SELECT ACCOUNTID, COUNT(*) TOTAL_TRANSACTION
FROM TRANSACTION
GROUP BY ACCOUNTID
ORDER BY TOTAL_TRANSACTION DESC LIMIT 1;

-- Branch with MAX transaction  

SELECT BRANCHID
FROM ACCOUNTS
WHERE ACCOUNTID=1003;

-- Which branch has teh highest loan exposure?

-- customer with MAX Loan amount

SELECT CUSTOMERID, SUM(LAONAMOUNT) HIGHEST_LOAN
FROM LOANS
GROUP BY CUSTOMERID
ORDER BY HIGHEST_LOAN DESC LIMIT 1;


-- Branch with MAX Loan Amount --

SELECT BRANCHID
FROM ACCOUNTS
WHERE CUSTOMERID= 104;

USE BANKING_SYSTEMDB;

USE BANKING_SYSTEMDB;

-- Function 

-- String Function --

-- CONCAT COMBINES MULTIPLE STRINGS 
SELECT CUSTOMERID, concat(FIRSTNAME," ",LASTNAME) AS FULL_NAME
FROM  CUSTOMERS; 

-- UPPER ()

-- IT CONVERTS THE CASES INTO UPPER CASES --

SELECT CUSTOMERID, UPPER(concat(FIRSTNAME," ",LASTNAME)) AS FULL_NAME
FROM  CUSTOMERS; 

-- LOWER ()

-- IT CONVERTS THE CASES INTO LOWER CASES --

SELECT CUSTOMERID, LOWER(concat(FIRSTNAME," ",LASTNAME)) AS FULL_NAME
FROM  CUSTOMERS; 

-- LENGTH()
-- FND THE NUMBER OF LEGHTH 

SELECT FIRSTNAME,LENGTH(FIRSTNAME) AS NAME_LENGTH
FROM CUSTOMERS
HAVING NAME_LENGTH <=5
ORDER BY NAME_LENGTH DESC LIMIT 1 OFFSET 1;

-- CHAR_LENGTH() --
SELECT FIRSTNAME, char_length(FIRSTNAME) AS CHARACTER_LENGTH
FROM CUSTOMERS;

-- LEFT () --
-- EXTRACTS THE DATA FROM LEFT SIDE

SELECT FIRSTNAME, LEFT(FIRSTNAME,3) AS FIRST_3_CHAR
FROM CUSTOMERS;

-- RIGHT()

-- EXTRACT THE DATA FROM THE RIGHT SIDE --

SELECT PHONE,right(PHONE,4) AS LAST4DIGITS
FROM CUSTOMERS;

-- DISPLAY MASKED ACCOUNT --

SELECT CUSTOMERID, CONCAT("XXXXX",RIGHT(PHONE,4)) AS MASKED_PHONE
FROM CUSTOMERS;

-- SUBSTRING() -- 

-- IT EXTRACTS THE PORTION OF A STRING 

SELECT EMAIL, substring(EMAIL,1,5) AS EMAIL_PART
FROM CUSTOMERS;

-- SUBSTRING_INDEX() -- 

-- IT EXTRACTS THE PORTION OF A STRING 

SELECT EMAIL, substring_index(EMAIL,"@",1) AS EMAIL_PART
FROM CUSTOMERS;

-- TRIM() -- 

-- REMOVES USELESS SPACES 

SELECT TRIM("Veena kutty  ") AS NAME;

-- REPLACE()
-- REPLACES THE VALUES -- 

SELECT EMAIL, REPLACE(EMAIL,'gmail.com','email.com') AS EMAILS
FROM CUSTOMERS;

-- LOCATE()--
-- FINDS  THE POSITION OF THE CHARACTER/STRING

SELECT EMAIL, LOCATE("@",EMAIL) AS POSITION 
FROM CUSTOMERS;

USE BANKING_SYSTEMDB;

-- Math Function  --

-- Round () Function--
-- rounds off the decimal values

SELECT ACCOUNTID,BALANCE,ROUND(BALANCE,0) AS ROUNDED_BALANCE 
FROM ACCOUNTS;

-- CEIL ()/CEILING() --
-- IT ROUNDS UP THE VALUE

SELECT BALANCE, CEIL(BALANCE) AS ROUNDUP_BALANCE
FROM ACCOUNTS;

-- FLOOR()
-- IT ROUNDS DOWN THE VALUE -- 

SELECT BALANCE, FLOOR(BALANCE) AS ROUNDDOWN_BALANCE
FROM ACCOUNTS;

-- ABS() --
-- RETURNS THE ABSOLUTE values

SELECT ABS(-8754) AS ABSOLUTE_VALUE;

-- MOD()
-- RETURNS REMAINING VALUE --

SELECT ACCOUNTID, MOD(ACCOUNTID,2) AS REMIANDER 
FROM ACCOUNTS;

-- CASE THEN END IS JUST LIKE IF --ELSE 

SELECT ACCOUNTID, MOD(ACCOUNTID,2) AS REMAINDER, CASE
WHEN MOD(ACCOUNTID,2)=0 THEN "Even"
ELSE "Odd"
END AS ID_TYPE
FROM ACCOUNTS;

-- POWER() -- 
-- WORKS LIKE INDICES

SELECT POWER(2,4) AS RESULT;

-- SQRT()
-- RETUNRS THE SQUARE ROOT OF THE VALUE 

SELECT BALANCE, SQRT(BALANCE) AS SQRT_BALANCE
FROM ACCOUNTS;

-- GREATEST() --
-- COMPARE VALUES

SELECT ACCOUNTID, BALANCE, greatest(BALANCE,25000) AS MINIMUM_BALANCE
FROM ACCOUNTS;

-- LEAST()
-- COMPARE VALAUE
SELECT ACCOUNTID, BALANCE, LEAST(BALANCE,25000) AS MAX_BALANCE
FROM ACCOUNTS;

-- CALCULATE ANNUAL INTREST

SELECT LOANID,LAONAMOUNT,INTERESTRATE, ROUND(LAONAMOUNT * INTERESTRATE /100,2) AS ANNUAL_INTEREST
FROM LOANS;

-- LOAN AMOUNT + INTEREST

SELECT LOANID,LAONAMOUNT,INTERESTRATE,
ROUND(LAONAMOUNT + (LAONAMOUNT * INTERESTRATE /100),2) AS PRINICIPAL_PLUS_ONEYEAR_INTEREST
FROM LOANS;

-- BALANCE CATEGORY--

SELECT ACCOUNTID, BALANCE,
CASE
WHEN BALANCE IS NULL THEN "UNKNOWN"
WHEN BALANCE < 10000 THEN "LOW"
WHEN BALANCE < 50000 THEN "MEDIUM"
ELSE "HIGH"
END AS BALANCE_CATEGORY
FROM ACCOUNTS;

-- DATE &  TIME FUNCTIONS

SELECT CURDATE() AS TODAY;  -- TODAY'S DATE
SELECT SYSDATE() AS TODAY; -- TODAY'S DATE  WITH TIME

-- YEAR()

SELECT CUSTOMERID, BIRTHDATE, YEAR(BIRTHDATE) AS BIRTH_YEAR
FROM CUSTOMERS;

-- MONTH ()

SELECT TRANSACTIONID, TRANSACTIONDATE, MONTH(TRANSACTIONDATE) AS TRANSACTION_MONTH 
FROM TRANSACTION;


-- MONTHNAME()

SELECT TRANSACTIONID, TRANSACTIONDATE, MONTHNAME(TRANSACTIONDATE) AS TRANSACTION_MONTH 
FROM TRANSACTION;

-- DAY()

SELECT TRANSACTIONID, TRANSACTIONDATE, DAY(TRANSACTIONDATE) AS DAY_NUMBER
FROM TRANSACTION;

-- DAYNAME()

SELECT TRANSACTIONID, TRANSACTIONDATE, DAYNAME(TRANSACTIONDATE) AS DAY_NAME
FROM TRANSACTION;

-- QUARTER()

SELECT TRANSACTIONID, TRANSACTIONDATE, QUARTER(TRANSACTIONDATE) AS QUARTER_NUMBER
FROM TRANSACTION;

SELECT QUARTER(TRANSACTIONDATE) AS QUARTERS, COUNT(*) AS TRANSACTION_COUNT,
SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTION
WHERE TRANSACTIONDATE IS NOT NULL
GROUP BY QUARTER(TRANSACTIONDATE);

-- DATEDIFF()

SELECT LOANID,STARTDATE,ENDDATE,DATEDIFF(ENDDATE,STARTDATE) AS LOAN_DAYS
FROM LOANS;

-- CALCULATE LOAN DURATION IN TERMS OF YEAR

SELECT LOANID, STARTDATE, ENDDATE , ROUND(DATEDIFF(ENDDATE, STARTDATE)/365,2) AS LAONS_YEARS
FROM LOANS
WHERE ENDDATE IS NOT NULL;

-- TIMESTAMPDIFF()

SELECT CUSTOMERID,FIRSTNAME,BIRTHDATE,TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) AS AGE
FROM CUSTOMERS;

-- AGE GROUP

SELECT CUSTOMERID,FIRSTNAME,BIRTHDATE,TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) AS AGE,
CASE
WHEN TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) <25 THEN "YOUNG ADULT"
WHEN TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) BETWEEN 25 AND 40 THEN "ADULT"
ELSE "SENIOR"
END AS AGE_GROUP
FROM CUSTOMERS;

-- DATE_FORMAT()

SELECT TRANSACTIONDATE, DATE_FORMAT(TRANSACTIONDATE,'%d-%m-%y') as FORMAT_DATE
FROM TRANSACTION;

SELECT TRANSACTIONDATE, DATE_FORMAT(TRANSACTIONDATE,'%M-%Y') as MONTH_YEAR
FROM TRANSACTION;

-- MONTHLY TRANSACTIONS

SELECT
DATE_FORMAT(TRANSACTIONDATE,'%Y-%m') AS MONTH,
COUNT(*) AS TRANSACTION_COUNTS,
SUM(AMOUNT) AS  TOTAL_AMOUNT
FROM TRANSACTION
WHERE TRANSACTIONDATE IS NOT NULL
GROUP BY DATE_FORMAT(TRANSACTIONDATE,'%Y-%m')
ORDER BY MONTH;

-- LAST 30 DAYS TRANSACTIONS 

SELECT* 
FROM TRANSACTION
WHERE TRANSACTIONDATE >= DATE_SUB(CURDATE(),INTERVAL 30 DAY);


SELECT * 
FROM TRANSACTION
WHERE TRANSACTIONDATE >=DATE_SUB('2026-02-25',INTERVAL 30 DAY);

-- ADDING DAYS TO THE DATE

SELECT TRANSACTIONID, TRANSACTIONDATE, DATE_ADD(TRANSACTIONDATE, INTERVAL 30 DAY) AS AFTER_30_DAYS
FROM TRANSACTION;

-- LOAN STATUS USING DAYS

SELECT LOANID, STARTDATE, ENDDATE,
CASE
WHEN ENDDATE IS NOT NULL THEN "NO END DATE"
WHEN ENDDATE < CURDATE() THEN "COMPLETED"
ELSE "ACTIVE"
END AS LOAN_STATUS
FROM LOANS;

-- Windows Function -- 

-- RANK() & DENSE_RANK & OVER()

SELECT LOANID, LAONAMOUNT, RANK() OVER(ORDER BY LAONAMOUNT DESC) AS LOAN_RANK
FROM LOANS;


SELECT TRANSACTIONID, AMOUNT,
RANK() OVER(ORDER BY AMOUNT DESC) AS TRANSACTION_RANK,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS TRANSACTION_DENSE_RANK
FROM TRANSACTION;

SELECT TRANSACTIONID, TRANSACTIONTYPE,AMOUNT,
DENSE_RANK() OVER(PARTITION BY TRANSACTIONTYPE ORDER BY AMOUNT DESC) AS TRNASACTION_RANK
FROM TRANSACTION;

-- ROW_NUMBER ()

SELECT LOANID, CUSTOMERID, LAONAMOUNT,
ROW_NUMBER() OVER(ORDER BY LAONAMOUNT DESC) AS ROWNUMBER
FROM LOANS;

-- SUM()

SELECT LOANID, CUSTOMERID,LAONAMOUNT,
SUM(LAONAMOUNT) OVER (ORDER BY LAONAMOUNT DESC) AS RUNNING_TOTAL
FROM LOANS;

SELECT LOANID, CUSTOMERID,LAONAMOUNT,
SUM(LAONAMOUNT) OVER (PARTITION BY CUSTOMERID ORDER BY LAONAMOUNT DESC) AS RUNNING_TOTAL
FROM LOANS;

-- LAG()

SELECT LOANID, CUSTOMERID, LAONAMOUNT,
LAG(LAONAMOUNT) OVER(ORDER BY LAONAMOUNT DESC) AS PREVIOUS_LAONAMOUNT
FROM LOANS;

-- LEAD()

SELECT LOANID, CUSTOMERID, LAONAMOUNT,
LEAD(LAONAMOUNT) OVER(ORDER BY LAONAMOUNT DESC) AS NEXT_LAONAMOUNT
FROM LOANS;


-- JOINS ---

-- INNER JOINS --

SELECT *FROM CUSTOMERS;
SELECT *FROM ACCOUNTS;

SELECT CUSTOMERS.CUSTOMERID, FIRSTNAME,ACCOUNTYPE,BALANCE
FROM CUSTOMERS
JOIN ACCOUNTS
ON CUSTOMERS.CUSTOMERID = ACCOUNTS.CUSTOMERID;

SELECT C.CUSTOMERID,C.FIRSTNAME, COUNT(A.ACCOUNTID) AS TOTAL_ACCOUNTS
FROM CUSTOMERS AS C
JOIN ACCOUNTS AS A 
ON C.CUSTOMERID = A.CUSTOMERID
GROUP BY C.CUSTOMERID;

-- LEFT JOIN 

SELECT BRANCHNAME, COUNT(ACCOUNTID) AS TOTAL_ACCOUNTS
FROM ACCOUNTS
LEFT JOIN BRANCHES
ON BRANCHES.BRANCHID =ACCOUNTS.BRANCHID
GROUP BY BRANCHNAME;

SELECT BRANCHNAME, COUNT(ACCOUNTID) AS TOTAL_ACCOUNTS
FROM BRANCHES
LEFT JOIN ACCOUNTS
ON BRANCHES.BRANCHID =ACCOUNTS.BRANCHID
GROUP BY BRANCHNAME;

-- RIGHT JOIN--

SELECT BRANCHNAME, COUNT(ACCOUNTID) AS TOTAL_ACCOUNTS
FROM BRANCHES
RIGHT JOIN ACCOUNTS
ON BRANCHES.BRANCHID =ACCOUNTS.BRANCHID
GROUP BY BRANCHNAME;

-- WHICH BRANCH HAS THE MOST CUSTOMERS/ACCOUNTS?

SELECT * FROM CUSTOMERS;
SELECT * FROM ACCOUNTS;
SELECT * FROM BRANCHES;


SELECT BRANCHES.BRANCHID,BRANCHNAME,
COUNT(ACCOUNTID) AS TOTAL_ACCOUNTS,
COUNT(CUSTOMERS.CUSTOMERID) AS TOTAL_CUSTOMERS
FROM ACCOUNTS
JOIN BRANCHES
ON ACCOUNTS.BRANCHID = BRANCHES.BRANCHID
JOIN CUSTOMERS
ON ACCOUNTS.CUSTOMERID =CUSTOMERS.CUSTOMERID
GROUP BY BRANCHES.BRANCHID
ORDER BY TOTAL_ACCOUNTS DESC LIMIT 1;

-- which branches has the highest loan exposure  

SELECT * FROM BRANCHES;
SELECT * FROM LOANS;
SELECT * FROM ACCOUNTS;
SELECT * FROM CUSTOMERS;

SELECT B.BRANCHID,BRANCHNAME, SUM(LAONAMOUNT) AS TOTAL_LOANS
FROM BRANCHES AS B 
JOIN ACCOUNTS AS A 
ON B.BRANCHID = A.BRANCHID
JOIN CUSTOMERS AS C
ON A.CUSTOMERID = C.CUSTOMERID
JOIN LOANS L
ON L.CUSTOMERID = C.CUSTOMERID
GROUP BY B.BRANCHID
ORDER BY TOTAL_LOANS DESC LIMIT 1;

