CREATE DATABASE BANKING_SYSTEMDB;
USE BANKING_SYSTEMDB;

SHOW DATABASES;
SHOW TABLES;

CREATE TABLE CUSTOMERS(
CUSTOMERID INT,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAIL VARCHAR(100),
PHONE VARCHAR(10));

DESCRIBE TABLE CUSTOMERS;
DESCRIBE CUSTOMERS;

SELECT *
FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN ACCOUNTCREATIONDATE DATE;

CREATE TABLE ACCOUNTS(
ACCOUNTID INT,
ACCOUNTYPE VARCHAR(20),
BALANCE DECIMAL(10,2));

CREATE TABLE TRANSACTION(
TRANSACTIONID INT,
TRANSACTIONDATE DATE,
AMOUNT DECIMAL(10,2),
TRANSACTIONTYPE VARCHAR(20));

CREATE TABLE BRANCHES(
BRANCHID INT,
BRANCHNAME VARCHAR(100),
BRANCHADDRESS VARCHAR(255),
BRANCHPHONE VARCHAR(20));

CREATE TABLE ACCOUNTBRANCHES(
ASSIGNEDATE DATE);

CREATE TABLE LOANS(
LOANID INT,
LAONAMOUNT DECIMAL(10,2),
INTERESTRATE DECIMAL (5,2),
STARTDATE DATE,
ENDDATE DATE);

SHOW TABLES;

ALTER TABLE CUSTOMERS
DROP COLUMN ACCOUNTCREATIONDATE;

SELECT *
FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN BIRTHDATE DATE;



ALTER TABLE CUSTOMERS
MODIFY PHONE VARCHAR(20),
ADD PRIMARY KEY (CUSTOMERID);

DESCRIBE CUSTOMERS;

SELECT *
FROM ACCOUNTS;

ALTER TABLE ACCOUNTS 
ADD CUSTOMERID INT;

ALTER TABLE ACCOUNTS
ADD CONSTRAINT 
FOREIGN KEY (CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);

DESCRIBE ACCOUNTS;

ALTER TABLE ACCOUNTS 
ADD PRIMARY KEY (ACCOUNTID);

ALTER TABLE TRANSACTION 
ADD ACCOUNTID INT,
ADD CONSTRAINT
FOREIGN KEY (ACCOUNTID)
REFERENCES ACCOUNTS(ACCOUNTID);


DESCRIBE ACCOUNTS;
DESCRIBE TRANSACTION;

ALTER TABLE TRANSACTION
ADD PRIMARY KEY (TRANSACTIONID);

DESCRIBE TRANSACTION;

ALTER TABLE BRANCHES
ADD PRIMARY KEY (BRANCHID);

ALTER TABLE ACCOUNTS
ADD BRANCHID INT,
ADD CONSTRAINT
FOREIGN KEY (BRANCHID)
REFERENCES BRANCHES(BRANCHID);

ALTER TABLE LOANS
ADD PRIMARY KEY (LOANID),
ADD CUSTOMERID INT,
ADD CONSTRAINT
FOREIGN KEY (CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);

ALTER TABLE  CUSTOMERS
MODIFY FIRSTNAME VARCHAR(50) NOT NULL,
MODIFY EMAIL VARCHAR(100) UNIQUE;

DESCRIBE CUSTOMERS;









